// <auto-generated />
namespace UrlShortener.Infrastructure.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class VanityUrl : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VanityUrl));
        
        string IMigrationMetadata.Id
        {
            get { return "201601141456511_Vanity Url"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
